[package]
name = "gdapi"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
sha1 = "0.10.6"

[dependencies.reqwest]
version = "0.13.1"
features = ["form"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dev-dependencies.tokio]
version = "1.49.0"
features = ["macros", "rt-multi-thread"]
