name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate
        run: cargo doc --no-deps

      - name: Upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: target/doc

      - name: Deploy
        uses: actions/deploy-pages@v4
